### ISSUE TITLE
Transpositions

### ISSUE THREAD

**Issue by RockPolish** [pathev/ChessTrainer#1]
Hi, are there plans to add support for transpositions? Basically if the same position can be reached in multiple ways, right now these positions are considered separate and so the same moves would have to be added multiple times (e.g. `1. d4 d5 2. c4 e6 3. Nf3 Nf6 4. Nc3` or `1. d4 d5 2. c4 e6 3. Nc3 Nf6 4. Nf3`). It would be super useful if it would recognize that it is the same position in both cases.

**Comment by pathev** [comment]
Hi,
It is somehow in my ToDo list, but I am not ready to support that.

**Comment by pathev** [comment]
Hi,
At last I tried something to cope with transpositions.
It adds comments in the PGN file.
Any node can be defined as a primary transposition.
Then, any leaf can be asked to be a secondary transposition, linked to a primary transposition.
The program searches automatically, through primary transpositions only, the first one that fits.

Edit : Now any node can be checked for transposition.

**Comment by pathev** [comment]
So I consider that done.

**Comment by RockPolish** [comment]
Sorry for the late response, I haven't had time to look at this. I just tried the current version and I've got a few questions:
Firstly I'm getting an error to do with the f strings in Transpositions.py on lines 57 and 142, but this was easily fixed by replacing the outer `"` by a `'` instead. Maybe this has to do with my Python version (3.11.4).
Secondly, I believe the "train" button is not working as intended when "read only" mode is not enabled, in that case it lets me just play any move and it'll add these moves, instead of only letting me play moves that are in the PGN. It does work when I enable read only and then click the training button.
Lastly, I may be misunderstanding how the transpositions work. My hope was that it would automatically recognize that it's a position that has already been reached before and show those moves, for example let's say I add to an empty file `1. e4 d5 2. d4 dxe4`, then if I also add `1. d4 d5 2. e4`, then I would hope that dxe4 already shows up because after the first 3 moves it's just the same position as before, if that makes sense.
Thanks for the update by the way - I've made extensive use of the previous version of the program and am hoping to update to include the new features once I figure them out!

**Comment by pathev** [comment]
Hi, thank you for your bug report.
And thank you very much for using my program (surely more than me).

1. I did not have an error with the f-string but I changed it anyway.
2. The problem with train during editing should be solved now.
3. Concerning transposition, the idea is not to find future transpositions but to link identical positions :
    - You first set primary position, e.g when on position 1. e4 d5 2. d4 dxe4 click on the anchor ;
    - Then, when on a transposition position (e.g 1. d4 d5 2. e4 dxe4), click on the link button ;
    - The program then checks primary positions and will link current position to one of them if possible.
4. I forgot to move to primary position when training, which should now be done.
